### ISSUE TITLE
Not building in Linux other than Debian

### ISSUE THREAD

**Issue by lf-araujo** [pixelspark/catena#130]
Building instructions are failing to find KituraTemplateEngine in Manjaro (Arch based) Linux:

![image](https://user-images.githubusercontent.com/10139950/40886376-18a6fd44-670d-11e8-9da9-d67b2813c28f.png)

```
 $  swift build
'Kitura' /tmp/catena/.build/checkouts/Kitura.git-3663189543328700261: error: product dependency 'KituraTemplateEngine' not found
'Kitura-net' /tmp/catena/.build/checkouts/Kitura-net.git--622939097078554517: error: product dependency 'CCurl' not found
warning: dependency 'Cryptor' is not used by any target

```
- Any suggestion on where should I sart to debug this?

I followed instructions as per project webpage: git clone & swift build

Thank you for this software.

**Comment by pixelspark** [comment]
@lf-araujo I did encounter this too - it appears there is a version of Kitura that has incorrect dependencies, and for some weird reason this is the version that gets selected by the package manager. Try removing the `Package.resolved` file and rebuilding - if that does not work, fiddling with the versions in `Package.swift` might fix it. I will have a look at this later!

**Comment by pixelspark** [comment]
A clean clone + `swift build` on Debian appears to work without issue. What version of Swift are you running?

Mine is `Swift version 4.0 (swift-4.0-RELEASE).`. Will now try a later one...

**Comment by lf-araujo** [comment]
![image](https://user-images.githubusercontent.com/10139950/41034167-2c1ad57c-695f-11e8-8954-bb41d50fb865.png)
It's 4.1.

Will try to debug following your suggestion.

Thank you!

**Comment by pixelspark** [comment]
I investigated this a bit further and indeed, it builds fine with 4.0 but fails against 4.1 or higher. Note however that it builds fine on Mac inside a recent XCode (running >=4.1) and `swift package generate-xcodeproj`, which is a bit odd.

**Comment by lf-araujo** [comment]
Thanks for waiting, 

I found the problem, it seems latest SPM allows for calling apt, which obviously does not work in other distros. An example code from SPM is:

```
import PackageDescription

let package = Package(
	name: "CCurl",
	providers: [
		.Brew("curl"), 
		.Apt("libcurl4-openssl-dev")
	]
)
```

From SPM sourcecode:


```
extension SystemPackageProviderDescription {
    public var installText: String {
        switch self {
        case .brew(let packages):
            return "    brew install \(packages.joined(separator: " "))\n"
        case .apt(let packages):
            return "    apt-get install \(packages.joined(separator: " "))\n"
        }
}
```

So this problem is upstream and I will close the issue. It is, however, a bit disappointing to see Apple is hardcoding apt into SPM.

Thank you

**Comment by pixelspark** [comment]
@lf-araujo as far as I know the '.apt' reference only causes the SPM to show a suggestion to obtain the required packages through apt, but does not actually call it. So this is unlikely to be the culprit here..
