### ISSUE TITLE
Cannot POST /api/query/.

### ISSUE THREAD

**Issue by swapnil-pandey** [pixelspark/catena#131]
I am using POSTMAN to access the api on `localhost:8338/api/query/`.

I have given the request body like this: 
```
{
	"sql": "select * from foo;",
	"database": "foo"
}
```
and have set the `Content-Type` as `application/json`.

I intend to receive the response of the sql statement but instead I receive a `Cannot POST /api/query/ - HTTP 404 Not Found` error!.

**Comment by pixelspark** [comment]
Does it work without the trailing `/`? Otherwise, try to use the web client and replicate the requests it makes...

**Comment by swapnil-pandey** [comment]
That's so silly of me. Removing the trailing `/` worked. Thanks!
